### ISSUE TITLE
trying to run godepgraph

### ISSUE THREAD

**Issue by ajpowel** [kisielk/godepgraph#12]
Hello -

I just cloned your project into my GitHub, & then tried to run it using your README guidance, & it doesn't work.

What am I doing incorrectly?

Here's the pertinent information:

$ pwd
/Users/ajpowel/GitHub/godepgraph

s986572:godepgraph ajpowel$ ls -lah
total 4312
drwxr-xr-x   8 ajpowel  SANDIA\Domain Users   272B May 18 12:20 ./
drwxr-xr-x   9 ajpowel  SANDIA\Domain Users   306B May 18 12:20 ../
drwxr-xr-x  13 ajpowel  SANDIA\Domain Users   442B May 18 12:20 .git/
-rw-r--r--   1 ajpowel  SANDIA\Domain Users   1.0K May 18 12:20 LICENSE
-rw-r--r--   1 ajpowel  SANDIA\Domain Users   1.8K May 18 12:20 README.md
-rw-r--r--   1 ajpowel  SANDIA\Domain Users   2.1M May 18 12:20 example.png
-rw-r--r--   1 ajpowel  SANDIA\Domain Users   6.9K May 18 12:20 example.svg
-rw-r--r--   1 ajpowel  SANDIA\Domain Users   4.0K May 18 12:20 main.go

I don't even see an executable, or anything to build.

What am I missing here?

Many thanks for any guidance you can offer!

Best,

AJP

**Comment by kisielk** [comment]
Did you follow the instructions in the readme?

Using `go install github.com/kisielk/godepgraph` should place the `godepgraph` executable in to your `$GOPATH/bin`

**Comment by TheBeachMaster** [comment]
This nolonger works
